version: '3'
services:
  nginx:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'SERVER_ROOT=${SERVER_ROOT}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_NGINX}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
volumes: {}
